public class Contenido implements IVisualizable { private String titulo; private String genero; private String creador; private int duracion; private boolean visto; public Contenido( ) { this.titulo = "Sin título"; this.creador = "Creador no encontrado"; this.genero = "Sin género"; this.duracion = 0; this.visto = false;
} public Contenido( String titulo, String creador ) { this.titulo = titulo; this.creador = creador; this.genero = "Sin género"; this.duracion = 0; this.visto = false; } public Contenido( String titulo, String genero, String creador, int duracion ) { this.titulo = titulo; this.genero = genero; this.creador = creador; this.duracion = duracion; this.visto = false; } public String getTitulo( ) { return titulo; } public void setTitulo( String titulo ) { this.titulo = titulo; } public String getGenero( ) { return genero; } public void setGenero( String genero ) { this.genero = genero; } public String getCreador( ) { return creador; } public void setCreador( String creador ) { this.creador = creador; } public int getDuracion( ) { return duracion; } public void setDuracion( int duracion ) { this.duracion = duracion; } @Override public void marcarVisto( ) {
this.visto = true; } @Override public boolean esVisto( ) { return visto; } @Override public int tiempoVisto( ) { return duracion; } }

public class Pelicula extends Contenido { private int año; public Pelicula( ) { super( ); this.año = 0; } public Pelicula( String titulo, String creador ) { super( titulo, creador ); this.año = 0; } public Pelicula( String titulo, String genero, String creador, int año, int duracion ) { super( titulo, genero, creador, duracion ); this.año = año; } public int getAño( ) { return año; } public void setAño( int año ) { this.año = año; }
@Override public String toString( ) { String pelicula = ""; pelicula += "Título: " + this.getTitulo( ) + "\n"; pelicula += "Género: " + this.getGenero( ) + "\n"; pelicula += "Creador: " + this.getCreador( ) + "\n"; pelicula += "Año: " + this.getAño( ) + "\n"; pelicula += "Duración: " + this.getDuracion( ) + " minutos\n"; if ( this.esVisto() ) { pelicula += "Visto: Si\n"; } else { pelicula += "Visto: No\n"; } return pelicula; } }

public class Serie extends Contenido { private int numeroTemporadas; public Serie( ) { super( ); this.numeroTemporadas = 1; } public Serie( String titulo, String creador ) { super( titulo, creador ); this.numeroTemporadas = 1; } public Serie( String titulo, String genero, String creador, int numeroTemporadas, int duracion ) { super( titulo, genero, creador, duracion ); this.numeroTemporadas = numeroTemporadas; } public int getNumeroTemporadas( ) { return numeroTemporadas;
} public void setNumeroTemporadas( int numeroTemporadas ) { this.numeroTemporadas = numeroTemporadas; } @Override public String toString( ) { String serie = ""; serie += "Título: " + this.getTitulo( ) + "\n"; serie += "Género: " + this.getGenero( ) + "\n"; serie += "Creador: " + this.getCreador( ) + "\n"; serie += "Temporadas: " + this.getNumeroTemporadas( ) + "\n"; serie += "Duración: " + this.getDuracion( ) + " minutos\n"; if ( this.esVisto() ) { serie += "Visto: Si\n"; } else { serie += "Visto: No\n"; } return serie; } }

public interface IVisualizable { public void marcarVisto( ); public boolean esVisto( ); public int tiempoVisto( ); }

public class Prueba { public static void main( String[] args ) { Pelicula[] peliculas = new Pelicula[5]; Serie[] series = new Serie[5]; peliculas[0] = new Pelicula( );
peliculas[1] = new Pelicula( "Halloween", "Terror", "Adam Sandler", 1998, 106 ); peliculas[2] = new Pelicula( "Vacaciones tranquilas", "Raúl Veraniego" ); peliculas[3] = new Pelicula( "Locos de amor", "Romance", "Victor Aristizabal", 2021, 98 ); peliculas[4] = new Pelicula( "Caparazón sin dientes", "Comedia", "Radamel Falcao", 2014, 151 ); series[0] = new Serie( "Los valientes", "Victor Aristizabal" ); series[1] = new Serie( "El templo perdido", "Aventura", "Adam Sandler", 10, 1080 ); series[2] = new Serie( ); series[3] = new Serie( "Ella y yo", "Romance", "Pedro Sarmiento", 2, 106 ); series[4] = new Serie( "Lo que ganamos los pobres", "Comedia", "James Rodriguez", 3, 240 ); peliculas[1].marcarVisto( ); peliculas[2].marcarVisto( ); peliculas[3].marcarVisto( ); series[0].marcarVisto( ); series[4].marcarVisto( ); Serie serieMasTemporadaSerie = series[0]; Pelicula peliculaMasRecientePelicula = peliculas[0]; System.out.println( "PELÍCULAS VISTAS..." ); for ( Pelicula pelicula : peliculas ) { if ( pelicula.esVisto() ) { System.out.println( " + " + pelicula.getTitulo() + ": Visto por " + pelicula.tiempoVisto() + " minutos." ); } if ( pelicula.getAño() > peliculaMasRecientePelicula.getAño() ) { peliculaMasRecientePelicula = pelicula; } } System.out.println( "\nSERIES VISTAS..." ); for ( Serie serie : series ) { if ( serie.esVisto() ) { System.out.println( " + " + serie.getTitulo() + ": Visto por " + serie.tiempoVisto() + " minutos." ); } if ( serie.getNumeroTemporadas() > serieMasTemporadaSerie.getNumeroTemporadas() ) { serieMasTemporadaSerie = serie; } }
System.out.println( "\n**********PELÍCULA MÁS RECIENTE**********" ); System.out.println( peliculaMasRecientePelicula.toString() ); System.out.println( "**********SERIE CON MÁS TEMPORADAS**********" ); System.out.println( serieMasTemporadaSerie.toString() );